import Head from 'next/head'
import styles from './Detail.module.css'
import { useRouter } from 'next/router'

const DetailView = ({ id }) => {
    const router = useRouter()
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className="titleGlobal">
                    Detail {id}
                </h1>
                <h1 onClick={() => router.back()}>
                    <span >Voltar</span>
                </h1>
            </main>

        </div>
    )
}

export default DetailView;