import Head from 'next/head'
import styles from './Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

const HomeView = () => {
    const router = useRouter()
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className="titleGlobal">
                    <a href="/">
                        Home
                    </a>
                </h1>
                <h1 className="titleGlobal">
                    <Link href="/detail">
                        Detail 0
                    </Link>
                </h1>
                <h1 className="titleGlobal">
                    <span onClick={() => router.push('/detail/88')}>Detail 88</span>
                </h1>
            </main>

        </div>
    )
}

export default HomeView;